# Generated by Django 5.0.4 on 2024-05-03 02:01

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='image',
            field=models.ImageField(null=True, upload_to=profiles.models.image_upload_location),
        ),
    ]
