# Generated by Django 5.0.2 on 2024-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_ID',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
