# Generated by Django 5.0.4 on 2024-06-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='registration_ID',
            field=models.CharField(blank=True, help_text='Also known as licences_ID', max_length=225, null=True, unique=True, verbose_name='license number'),
        ),
    ]
