# Generated by Django 5.0.2 on 2024-05-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='website',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
