# Generated by Django 5.0.2 on 2024-05-02 17:46

import address.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('profiles', '0003_remove_userprofile_registration_id_agentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='registration_ID',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='company_address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
