# Generated by Django 5.0.2 on 2024-06-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_agentprofile_registration_id_referral'),
        ('profiles', '0004_remove_userprofile_slug'),
    ]

    operations = [
    ]
