# Generated by Django 5.0.2 on 2024-05-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_contractorprofile_website'),
        ('profiles', '0004_alter_agentprofile_address_and_more'),
    ]

    operations = [
    ]
