# Generated by Django 5.0.2 on 2024-05-03 15:59

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_merge_20240503_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='image',
            field=models.ImageField(null=True, upload_to=profiles.models.image_upload_location),
        ),
    ]
