# Generated by Django 5.0.2 on 2024-06-13 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_merge_20240610_1217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(help_text='The referral code.', max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.ManyToManyField(help_text='The users who have been referred.', related_name='referred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.OneToOneField(help_text='The user who made the referral.', on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL),
        ),
    ]
