# Generated by Django 5.0.2 on 2024-06-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_referral_options_alter_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='has_seen_onboarding_message',
        ),
    ]
