# Generated by Django 5.0.2 on 2024-07-30 14:28

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_agentprofile_has_seen_onboarding_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='image',
            field=models.ImageField(null=True, upload_to=profiles.models.image_upload_location_agent),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to=profiles.models.image_upload_location_home_owner),
        ),
    ]
