# Generated by Django 5.0.2 on 2024-10-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_agentprofile_image_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='company_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
