# Generated by Django 5.0.2 on 2024-12-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_agentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='insurance_number',
            field=models.CharField(default='12345678', max_length=255),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='license_number',
            field=models.CharField(default='12345678', max_length=225),
        ),
    ]
