# Generated by Django 5.0.2 on 2024-12-11 11:24

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_contractorprofile_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorprofile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='address',
            field=models.CharField(default='Nigeria', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='registration_ID',
            field=models.CharField(default='12345678', help_text='Also known as licences_ID', max_length=225, unique=True, verbose_name='license number'),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='company_address',
            field=models.CharField(default='Nigeria', max_length=50),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='company_name',
            field=models.CharField(default='belize', max_length=255),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=225),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='specialization',
            field=models.CharField(default='coding', max_length=225),
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=225)),
                ('company_address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=225)),
                ('image', models.ImageField(null=True, upload_to=profiles.models.image_upload_location_contractor)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
