# Generated by Django 5.0.2 on 2024-12-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_contractorprofile_registration_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='address',
            new_name='agent_address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='home_owner_address',
        ),
    ]
