# Generated by Django 5.0.2 on 2025-01-10 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_address_agentprofile_agent_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractorprofile',
            old_name='city',
            new_name='address',
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='hired',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagereceiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagesender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sender', 'receiver'], name='profiles_me_sender__1947d4_idx')],
            },
        ),
    ]
