# Generated by Django 5.0.4 on 2025-01-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_agentprofile_invited_home_owners_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='invited_home_owners',
            new_name='agent_invited_home_owners',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='invited_agents',
            new_name='home_owner_invited_agents',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_associated_contarctors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_associated_contarctors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_owner_associated_contarctors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='associated_contarctors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
