# Generated by Django 5.0.4 on 2025-01-28 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_remove_userprofile_home_owner_associated_contarctors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='home_owner_associated_contarctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='associated_contarctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_owner_invited_agents',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
