# Generated by Django 5.0.4 on 2025-02-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_userprofile_home_owner_associated_contarctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='country',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='registration_ID',
            field=models.CharField(help_text='Also known as licences_ID', max_length=225, unique=True, verbose_name='license number'),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='company_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='country',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='insurance_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='license_number',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='specialization',
            field=models.CharField(max_length=225),
        ),
    ]
