# Generated by Django 5.0.4 on 2025-03-04 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_agentprofile_agent_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_associated_contarctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_associated_contarctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_invited_home_owners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_home_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
