# Generated by Django 5.0.4 on 2025-03-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_chatroominvitation_room_delete_chatroom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
