# Generated by Django 5.0.4 on 2025-03-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_invitation_delete_referral'),
        ('profiles', '0022_delete_message'),
    ]

    operations = [
    ]
