# Generated by Django 5.0.4 on 2025-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
