# Generated by Django 5.0.4 on 2025-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatroom_room_type_alter_chatroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('group_chat', 'Group'), ('private', 'Private'), ('broadcast', 'Broadcast')], default='private', max_length=20),
        ),
    ]
