# Generated by Django 5.0.4 on 2025-03-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_chatroom_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('group_chat', 'Group'), ('private', 'Private'), ('broadcast_ho', 'BroadcastHO'), ('broadcast_co', 'BroadcastCO'), ('broadcast_ag', 'BroadcastAG'), ('broadcast_iv', 'BroadcastIV')], default='private', max_length=20),
        ),
    ]
