# Generated by Django 5.0.2 on 2024-04-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContractorProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
