# Generated by Django 5.0.2 on 2024-12-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
