# Generated by Django 5.0.2 on 2024-04-18 15:50

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to=main.models.image_upload_location)),
                ('file', models.FileField(null=True, upload_to=main.models.file_upload_location)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='contenttypes.contenttype')),
            ],
        ),
    ]
