# Generated by Django 5.0.4 on 2025-02-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_media_media_type_media_video_alter_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
