# Generated by Django 5.0.4 on 2025-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_media_media_type_media_video_alter_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image_category',
            field=models.CharField(blank=True, choices=[('before', 'Before'), ('after', 'After')], max_length=10, null=True),
        ),
    ]
