# Generated by Django 5.0.4 on 2025-02-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_media_file_url_media_public_id'),
        ('main', '0003_media_image_category'),
    ]

    operations = [
    ]
