<<<<<<< HEAD
# Generated by Django 5.0.4 on 2025-03-04 16:02
=======
# Generated by Django 5.0.4 on 2025-03-05 17:32
>>>>>>> 4d1634c2a5c17c4b53837e909e4cc6949af8c2fd

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20250228_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_category',
            field=models.CharField(blank=True, choices=[('before', 'Before'), ('after', 'After')], default='before', max_length=10, null=True),
        ),
    ]
