# Generated by Django 5.0.4 on 2025-03-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_roommembership'),
        ('main', '0005_alter_media_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chat.message'),
            preserve_default=False,
        ),
    ]
