# Generated by Django 5.0.4 on 2025-03-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_media_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='message',
        ),
    ]
