# Generated by Django 5.0.4 on 2025-03-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_deleted'),
        ('main', '0007_remove_media_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=1024)),
                ('public_id', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('Image', 'Image'), ('File', 'File'), ('Video', 'Video')], default='Image', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagemedia', to='chat.message')),
            ],
        ),
    ]
