# Generated by Django 5.0.4 on 2025-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_messagemedia_file_name_messagemedia_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('video', 'Video')], default='image', max_length=20),
        ),
    ]
