# Generated by Django 5.0.4 on 2024-05-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedaccount',
            options={},
        ),
    ]
