# Generated by Django 5.0.2 on 2024-05-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedaccount',
            options={},
        ),
    ]
