# Generated by Django 5.0.4 on 2025-02-27 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_userprofile_home_owner_associated_contarctors_and_more'),
        ('property', '0002_alter_assignedaccount_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condominium', 'Condominium'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial')], default='house', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('half_bath', models.PositiveIntegerField(blank=True, null=True)),
                ('full_bath', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('square_footage', models.PositiveIntegerField(blank=True, null=True)),
                ('total_square_foot', models.PositiveIntegerField(blank=True, null=True)),
                ('lot_size', models.PositiveIntegerField(blank=True, null=True)),
                ('scope_of_work', models.TextField(default='explain your scope of work')),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('basement_details', models.TextField(blank=True, null=True)),
                ('garage', models.CharField(blank=True, choices=[('attached', 'Attached'), ('detached', 'Detached'), ('none', 'None')], max_length=50, null=True)),
                ('repair_recommendations', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Status: Pending (new listing), In Progress (contractor assigned), Completed (work finished).', max_length=20)),
                ('contractors', models.ManyToManyField(blank=True, help_text='Contractors assigned to this property.', related_name='assigned_contractors', to='profiles.contractorprofile')),
                ('home_owner_agents', models.ManyToManyField(blank=True, related_name='home_owner_agents', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, help_text='Investors who have liked this property.', related_name='liked_properties', to=settings.AUTH_USER_MODEL)),
                ('property_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
