# Generated by Django 5.0.4 on 2025-03-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_is_first_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_first_property',
            field=models.BooleanField(default=True, help_text="Indicates if this is the property owner's first property."),
        ),
    ]
