# Generated by Django 5.0.4 on 2025-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_is_first_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_quotes',
            field=models.BooleanField(default=False, help_text='Indicates if the property has a quotes on it.'),
        ),
    ]
