# Generated by Django 5.0.2 on 2024-04-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_quoterequests_quoterequest_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='quote_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_project', to='quotes.quoterequest'),
        ),
    ]
