# Generated by Django 5.0.2 on 2024-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quoterequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
