# Generated by Django 5.0.4 on 2025-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quoterequest_proprosed_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='renovation',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='proprosed_price',
            new_name='proprosed_budget',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='returned_price',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='renovation_type',
            field=models.CharField(blank=True, choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='returned_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Renovation',
        ),
    ]
