# Generated by Django 5.0.4 on 2024-06-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quoterequest_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='slug',
        ),
    ]
