# Generated by Django 5.0.4 on 2025-02-27 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_userprofile_home_owner_associated_contarctors_and_more'),
        ('quotes', '0003_remove_property_renovation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='total_square_footage',
            new_name='total_square_foot',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condominium', 'Condominium'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial')], default='house', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='repair_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='scope_of_work',
            field=models.TextField(default='explain your scope of work'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Status: Pending (new listing), In Progress (contractor assigned), Completed (work finished).', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='contractors',
            field=models.ManyToManyField(blank=True, help_text='Contractors assigned to this property.', related_name='assigned_contractors', to='profiles.contractorprofile'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.CharField(blank=True, choices=[('attached', 'Attached'), ('detached', 'Detached'), ('none', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Investors who have liked this property.', related_name='liked_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='quote_type',
            field=models.CharField(choices=[('RTS', 'Renovate To Sell'), ('RTR', 'ExterioRenovate To Rent'), ('RTO', 'ExterioRenovate To Own')], default='RTS', max_length=355),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Returned', 'Returned'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
