# Generated by Django 5.0.4 on 2025-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_property_renovation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='quote_type',
            field=models.CharField(choices=[('RTS', 'Renovate To Sell'), ('RTR', 'ExterioRenovate To Rent'), ('RTO', 'ExterioRenovate To Own')], default='RTS', max_length=355),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Returned', 'Returned'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
