# Generated by Django 5.0.4 on 2025-02-27 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property'),
        ('quotes', '0004_rename_tittle_property_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_properties', to='property.property'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
