# Generated by Django 5.0.2 on 2024-04-10 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_project_is_approved_quoterequest_is_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
