# Generated by Django 5.0.4 on 2025-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_property_has_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='estimated_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='ROI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='estimated_timeline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='sproosts_ARV',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
