# Generated by Django 5.0.2 on 2024-04-19 05:55

import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quoterequest_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=quotes.models.upload_location),
        ),
    ]
