# Generated by Django 5.0.2 on 2024-07-30 14:28

import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_remove_quoterequest_created_by_home_owners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=quotes.models.upload_location_quote),
        ),
    ]
