# Generated by Django 5.0.4 on 2025-02-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_quoterequest_property_delete_property'),
        ('quotes', '0006_property_estimated_budget_quoterequest_roi_and_more'),
    ]

    operations = [
    ]
