# Generated by Django 5.0.2 on 2024-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quoterequest_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='contact_username',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
