# Generated by Django 5.0.2 on 2024-10-04 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_remove_quoterequest_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='created_by_agent',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quote_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='user',
            field=models.ForeignKey(help_text='the user who created the quote', on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
