# Generated by Django 5.0.2 on 2025-01-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_renovation_bid_listing_projectpictures_referral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='quote_request',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quote_properties', to='quotes.property'),
            preserve_default=False,
        ),
    ]
