# Generated by Django 5.0.2 on 2025-01-10 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_remove_project_quote_request_quoterequest_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='contact_username',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='property_address',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='contractors',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, related_name='quote_contractors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
