# Generated by Django 5.0.2 on 2025-01-10 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_rename_city_contractorprofile_address_and_more'),
        ('quotes', '0013_alter_quoterequest_contractors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='contractors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_contractors', to='profiles.contractorprofile'),
        ),
    ]
