# Generated by Django 5.0.2 on 2025-01-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_rename_city_contractorprofile_address_and_more'),
        ('quotes', '0017_alter_quoterequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='quote_for',
        ),
        migrations.AddField(
            model_name='property',
            name='property_owner',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
