# Generated by Django 5.0.2 on 2025-01-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_remove_property_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='renovation',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='renovation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovations', to='quotes.renovation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.CharField(blank=True, choices=[('pending', 'Pending')], max_length=50, null=True),
        ),
    ]
