# Generated by Django 5.0.4 on 2025-01-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_alter_property_property_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
    ]
