# Generated by Django 5.0.4 on 2025-01-28 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_remove_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='home_owner_agents',
            field=models.ManyToManyField(blank=True, related_name='home_owner_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quote_type',
            field=models.CharField(choices=[('RTS', 'Renovate To Sell'), ('RTR', 'ExterioRenovate To Rent'), ('RTO', 'ExterioRenovate To Own')], default='RTS', max_length=355),
            preserve_default=False,
        ),
    ]
