# Generated by Django 5.0.4 on 2025-01-28 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_property_home_owner_agents_quoterequest_quote_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='investors who have liked this properties.', related_name='liked_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='tittle',
            field=models.CharField(default='onitsha', max_length=255),
            preserve_default=False,
        ),
    ]
