# Generated by Django 5.0.4 on 2025-01-30 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0024_property_likes_property_tittle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='renovation',
        ),
        migrations.AddField(
            model_name='property',
            name='contractors',
            field=models.ManyToManyField(blank=True, help_text='Contractors assigned to this property.', related_name='assigned_contractors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='renovation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovations', to='quotes.renovation'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
